language: c
os: linux
dist: xenial
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
env:
  global:
    - PACKAGE=cs_api_client
    - OCAML_VERSION=4.08
    - PINS="cohttp:ocaml-cohttp cohttp-lwt:ocaml-cohttp cohttp-lwt-unix:ocaml-cohttp conduit:ocaml-conduit conduit-lwt:ocaml-conduit conduit-lwt-unix:ocaml-conduit"
  jobs:
    - DISTRO=debian-10
    - DISTRO=centos-7
script:
  - bash .travis-docker.sh
before_deploy:
  - docker run --env-file=env.list --env DISTRO -v $(pwd):/repo local-build bash .travis-release.sh
  - export RELEASE_ARCHIVE=$(ls *.tar.gz)
  - echo "Releasing $RELEASE_ARCHIVE to GitHub Releases"
deploy:
  provider: releases
  token:
    secure: VKhHoF2/CWLmvSWMNkymRgMmfg0uGVi6UxXx3OEbC7R+zgoGRnAJkPFdABHoQ00jJ/Fob6uB0XbAJPeK1ic3kWJMzBGeuCiGL4hJH6f7RRRWcimFJBy08H2WlTTxK/gJipKIJs7SkPkMHYxvmog3XzjH2pvHEN7YKDiu3GA3EmBnoliiGnvb/IExShW2r0NsfZ1K0kiYWSr4n9TyKi4DINxAnv1j8NQWi5WiB1Wu9NpflR4oZhZu0Frz8VaNtVS5GE9k66S1igAOBQdS5jPBHN2aTN9/w3VU0yYIfgUNu8f9PTW4RobJY62MnikSSMD6GOFjpoDoi9eZH1TxCC8kAakmRHsKo5XxRWOWcIFHarN7w0zCdgelPNDQyMcwM0uWArNedaB83r+GFgP1n6xp6LnO1TK2B/lybs+XkeBjsPQv+cClqiBa4fx3um6U59xoFtxwUUCAH+0D8CcaIO+EsvVU2TY/7LP5hKKtffmDuhFWIL9auv5x9lnd1M2Jo2H9DAqH25uXHYFHP7t8xJVlIUI3gjoYXRaZkKV5CzLkVsytRagmPlutNn6g3rDwhGAbzPuftyuYXQKq/F9wr54FXuGshytcdQ/ciOHieqt6JDBiYiQQHM4aqh9JOuMN/PxOIPbpihw0+GXv/09or3T0vLLty2paRJgb13zJ4zg22Ro=
  file_glob: true
  file: "${RELEASE_ARCHIVE}"
  skip_cleanup: true
  on:
    repo: bbc2/api-client
    tags: true
