language: c
os: linux
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
env:
  global:
    - PACKAGE=cs_api_client
    - OCAML_VERSION=4.08
    - PINS="cohttp:ocaml-cohttp cohttp-lwt:ocaml-cohttp cohttp-lwt-unix:ocaml-cohttp conduit:ocaml-conduit conduit-lwt:ocaml-conduit conduit-lwt-unix:ocaml-conduit"
  jobs:
    - DISTRO=debian-10
    - DISTRO=centos-7
script:
  - bash .travis-docker.sh
before_deploy:
  - docker run --env-file=env.list --env DISTRO -v $(pwd):/repo local-build bash .travis-release.sh
  - export RELEASE_ARCHIVE=$(ls *.tar.gz)
  - echo "Releasing $RELEASE_ARCHIVE to GitHub Releases"
deploy:
  provider: releases
  token:
    secure: XEo8BCj3cuUhWY+PJNsnjl7+FTi7+fCuWELVbQGydLvN5Ah9yjuydPQ+jlOCBK61lIXETNFAv8Fm6yP/Af2UGM64jq6mvNal1VB3L7b3SgZgIZsXlsoiTloOS9yz3JGxklVuXJXt3J7qNzfdwTAxbtvIgUPgGilakPWCPBUUyENtyHgRoIFnlm52HrpEMrIiavE9tjUBL/JU62zYRG4oiwzw62paowEjSoxOD1aIIFjNY1UIwhx6jRCZQmPtdlTAVxP/iiwsWY6N4dQaiPK48HuFAXRmOfzNZc1FPNMh61rNKBMDBv5lN2uIw28aKMmo4w7bVW+hgANlJTDbgkjPcBk+miLz270zKBOpgEPv7YurKoHOdhHE5BTTDshGEDpyDwy1P//U/I5Hso7YqNvrqikKXMt0ZESeZxLuatPFDba+YORG1Zj1FLFt4TpWjuHSqergbNfpwPtVdR0AtuDhsCv5Lxi4ILdhuNmVM3SZHyArm1UyVaA72BacU5yzf2es5JSaLQg+IuzOd5jtyOvUFIfkB5+W/TgF6h6KeuD1isP2dbfAC6KaVhPM8dtSuz5UbqSzF+biRCEAlIoWbCJUmRnRlZXXpvKtL1b7MYywsgYVQ12uNtSdH+v2THN3Zlu7+4pKyYFMyevMKpFThyLPovf7YGhUC9nG+fZ4zmkJzeo=
  file_glob: true
  file: "${RELEASE_ARCHIVE}"
  skip_cleanup: true
  on:
    repo: cryptosense/api-client
    tags: true
